services:
  - type: web
    name: intellirag-api
    env: docker
    dockerfilePath: ./Dockerfile
    region: ohio
    plan: free
    healthCheckPath: /
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: VECTOR_STORE_DIR
        value: ./vector_store
      - key: UPLOAD_DIR
        value: ./uploads
      - key: DATABASE_URL
        value: sqlite:///./rag_app.db